language: ruby
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: PEFeuHTzYeYBf5Kx+8udL4EKPXXxSsdbMUNiJAGpFyco02OawwK++jx+ZxraH/Uq4LgbUyh+eWQ7oKZ79D2RN2V7ccBRVacy0Jo61R+5qijcAFpY3M6x7t8G4HPaVamI6/78YtEM12JVSY5VgNP1mWlTWcIPU2V5FKPsqBmfgpjUF1da9bhtXyHqXExaA+gjzcIkip8rVeX6jNzuxX+KmW33N+5sF7l+Yejix5HsA/3bi+EvVvnsBBylov/zCf0upsD89+vAVn3KZHf2JuyWjJk9PMMPI4JKxEL6kASx7UHtdhwwWfTItVxp8Fnr7ghbLWt1OMRDD5uk3lzv6Rog4CrW1uEf+QScgqlbu4UxpEV4JGNh0eT9JiPpj2eNVsBk3X/baGN5juGyVP5nYIHaAwvEtZV5YpwO2pyLO76Wsy/vNcqozuVcfEjGpg4Mq4D9834OeTyZQmEo4lI/7wgl4i639Fu9eGtSLFQTYXGylTUNF1sLRGm2/45Q+lu1PdCuLqCU5AyHpNFrCI+S8xAmyNFuurxzhpzTCALIJMhrEz/843nMEWJImvP/TRexkZrunIGsBGKvhdwwwlSu6VF+ZOemdmXUq9GobfVVRMB86KqrUWG4+F0ULbKXFG0HBuSWXhxbR5FC57MFIfhkQCfA4IZbZ8931TzL/iWozoAMgUY=
  - secure: iHtVLiMWkQhkmPzmegsoAUSP7ai+Xztuz1QirEZp77X0969uIJECzUaQpEk+gDkS/d+g+uR9kj4jLn9BVnMtKd7BmC04dL3RYjFrtApxRm3aAQd4Xrbx9MzYaHBKuCP8J8SQVIkocn6TWR3Fik5LRMzMaSzkBw51NRzLXFXycuBUhveVd//GiwukkNckYEi6g3TfGL4n2R0LqfKHonmZuK4rKb5fENlcytCBdkYpqNgX82HsZ2UkUXfNOFecyvxrEsi8Bew6mwGJvqLFEijIlZMrDWKsdpSFQr0a+FbY9D4zwr1CQMlKKUJrH0rsGYC5aQgmb0xVPNj+1o05kHVigbjiIUHnHIQubfcoZu4Ku4LEmwyajoT2hFsIHlb6wlYId8fYl/lgb50YKThYu8mI3g6nnQj7s2Tqk3evmm+ZiW5J3zB2hg540uwGPKYkWWTlxt03PYWdYx93OA036oAW9c7odoKpEHoAg54e+9IBWtF6qM4IKjduR7i+aEzTi1/Ji31ScRtQkqvck4gC353DlPGW3UVEFCrxTbYapbiXa1A0VGORIpUWBj1QVJYZ9uJkgU90eLBi2UA4FB7MUjBojaovORyj1dAEyXdZOahQXb+2pPmNVlGEyz3QtdDefW8RGOilXt6xGjTafhIE+iB5oqgz2eMwdq7yRkJloMyekzE=
sudo: false
exclude:
- vendor
branches:
  only:
  - master
