language: ruby
rvm:
- 2.4.2
install:
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: PEFeuHTzYeYBf5Kx+8udL4EKPXXxSsdbMUNiJAGpFyco02OawwK++jx+ZxraH/Uq4LgbUyh+eWQ7oKZ79D2RN2V7ccBRVacy0Jo61R+5qijcAFpY3M6x7t8G4HPaVamI6/78YtEM12JVSY5VgNP1mWlTWcIPU2V5FKPsqBmfgpjUF1da9bhtXyHqXExaA+gjzcIkip8rVeX6jNzuxX+KmW33N+5sF7l+Yejix5HsA/3bi+EvVvnsBBylov/zCf0upsD89+vAVn3KZHf2JuyWjJk9PMMPI4JKxEL6kASx7UHtdhwwWfTItVxp8Fnr7ghbLWt1OMRDD5uk3lzv6Rog4CrW1uEf+QScgqlbu4UxpEV4JGNh0eT9JiPpj2eNVsBk3X/baGN5juGyVP5nYIHaAwvEtZV5YpwO2pyLO76Wsy/vNcqozuVcfEjGpg4Mq4D9834OeTyZQmEo4lI/7wgl4i639Fu9eGtSLFQTYXGylTUNF1sLRGm2/45Q+lu1PdCuLqCU5AyHpNFrCI+S8xAmyNFuurxzhpzTCALIJMhrEz/843nMEWJImvP/TRexkZrunIGsBGKvhdwwwlSu6VF+ZOemdmXUq9GobfVVRMB86KqrUWG4+F0ULbKXFG0HBuSWXhxbR5FC57MFIfhkQCfA4IZbZ8931TzL/iWozoAMgUY=
sudo: false
exclude:
- vendor

branches:
  only:
    - master
