# Jykell configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: Shri Radha Krishna
description: Dedicated to the eternal couple Radha Krishna. Radha Krishna love stories, beautiful illustrations, mantras, Srimad Bhagavatam and Bhagavad Gita teachings and much more...
cover: assets/images/radhakrishnahanuman-3.jpg
logo: assets/images/shriradhakrishna.png
logo_dark: assets/images/krishna.png
favicon: assets/images/krishna.png
production_url: https://shriradhakrishna.com/
source_url: https://github.com/krishnablog/krishnablog.github.io

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
# twitter: hanumanblog # replace by your username
facebook: radhakrishnablog # replace by your username

# Disqus
disqus: True
disqus_name: radha-krishna # replace by your username

# Google Analytics
google_analytics: UA-110255634-1 # replace by your GA id

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed]
exclude: [vendor]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: krishnablog
repo: krishnablog.github.io
branch: master
relative_source: ../shriradhakrishna/
destination: ../shriradhakrishna-pages/
production_url:  https://shriradhakrishna.com/
source_url:  https://github.com/krishnablog/krishnablog.github.io

url: "https://shriradhakrishna.com"
plugins:
  - jekyll-sitemap
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
